export type Course = {
  title: string;
  provider: string;
  level: string;
  duration: string;
  rating: number;
  url: string;
  /** All courses listed here are free to learn (no paywall for core content). */
  free: boolean;
};

export type CareerField = {
  slug: string;
  name: string;
  icon: string;
  tagline: string;
  demand: "Very High" | "High" | "Growing" | "Stable";
  avgSalary: string;
  skills: string[];
  courses: Course[];
  projects: string[];
  certifications: string[];
};

const FREE = true;

export const CAREER_FIELDS: CareerField[] = [
  {
    slug: "software-development",
    name: "Software Development",
    icon: "Code2",
    tagline: "Build applications, backends and systems with modern stacks.",
    demand: "Very High",
    avgSalary: "$90k – $160k",
    skills: ["Data Structures", "Algorithms", "Git", "System Design", "Testing", "APIs"],
    courses: [
      { title: "The Odin Project – Full Stack Path", provider: "The Odin Project", level: "Beginner", duration: "Self-paced", rating: 4.9, url: "https://www.theodinproject.com/", free: FREE },
      { title: "Back End Development and APIs", provider: "freeCodeCamp", level: "Beginner", duration: "~300h", rating: 4.8, url: "https://www.freecodecamp.org/learn", free: FREE },
      { title: "System Design Primer", provider: "GitHub (open source)", level: "Intermediate", duration: "Self-paced", rating: 4.9, url: "https://github.com/donnemartin/system-design-primer", free: FREE },
    ],
    projects: ["REST API with auth + tests", "Real-time chat app", "URL shortener with analytics"],
    certifications: ["Meta Back-End Developer", "AWS Certified Developer – Associate"],
  },
  {
    slug: "web-development",
    name: "Web Development",
    icon: "Globe",
    tagline: "Frontend, backend and full-stack web apps.",
    demand: "Very High",
    avgSalary: "$75k – $140k",
    skills: ["HTML/CSS", "JavaScript", "React/Next.js", "Node.js", "Tailwind", "Databases"],
    courses: [
      { title: "Full Stack Open", provider: "University of Helsinki", level: "Beginner", duration: "Self-paced", rating: 4.9, url: "https://fullstackopen.com/en/", free: FREE },
      { title: "Responsive Web Design", provider: "freeCodeCamp", level: "Beginner", duration: "~300h", rating: 4.8, url: "https://www.freecodecamp.org/learn", free: FREE },
      { title: "MDN Web Docs Tutorials", provider: "MDN (Mozilla)", level: "Beginner", duration: "Self-paced", rating: 4.9, url: "https://developer.mozilla.org/", free: FREE },
    ],
    projects: ["Portfolio + blog with CMS", "E-commerce store with payments", "SaaS dashboard with auth"],
    certifications: ["Meta Front-End Developer", "AWS Cloud Practitioner"],
  },
  {
    slug: "python",
    name: "Python",
    icon: "FileCode",
    tagline: "Scripting, automation, backends and data.",
    demand: "Very High",
    avgSalary: "$85k – $150k",
    skills: ["Python", "OOP", "APIs", "Pandas", "Django/Flask", "Testing"],
    courses: [
      { title: "Python for Everybody", provider: "py4e.com (Dr. Chuck)", level: "Beginner", duration: "Self-paced", rating: 4.9, url: "https://www.py4e.com/", free: FREE },
      { title: "Scientific Computing with Python", provider: "freeCodeCamp", level: "Beginner", duration: "~300h", rating: 4.8, url: "https://www.freecodecamp.org/learn", free: FREE },
      { title: "Official Django Tutorial", provider: "Django Project", level: "Intermediate", duration: "Self-paced", rating: 4.8, url: "https://docs.djangoproject.com/en/stable/intro/tutorial01/", free: FREE },
    ],
    projects: ["Automation toolkit", "Django REST marketplace", "Data analysis notebook pack"],
    certifications: ["PCAP Python Associate", "Django / DRF portfolio"],
  },
  {
    slug: "java",
    name: "Java",
    icon: "Coffee",
    tagline: "Enterprise backends, Android and Spring systems.",
    demand: "High",
    avgSalary: "$85k – $145k",
    skills: ["Java", "Spring Boot", "SQL", "Microservices", "JUnit", "Kafka"],
    courses: [
      { title: "Java Programming (Parts I & II)", provider: "University of Helsinki MOOC", level: "Beginner", duration: "Self-paced", rating: 4.9, url: "https://java-programming.mooc.fi/", free: FREE },
      { title: "Spring Official Guides", provider: "Spring.io", level: "Intermediate", duration: "Self-paced", rating: 4.8, url: "https://spring.io/guides", free: FREE },
      { title: "Java Algorithms & Data Structures", provider: "freeCodeCamp", level: "Intermediate", duration: "Self-paced", rating: 4.7, url: "https://www.freecodecamp.org/learn", free: FREE },
    ],
    projects: ["Banking REST API (Spring)", "Inventory microservices", "Android expense tracker"],
    certifications: ["Oracle Certified Associate: Java", "Spring Certified Professional"],
  },
  {
    slug: "cpp-c",
    name: "C / C++",
    icon: "Cpu",
    tagline: "Systems, embedded, game engines and performance.",
    demand: "High",
    avgSalary: "$90k – $155k",
    skills: ["C", "C++", "Memory Management", "STL", "Multithreading", "CMake"],
    courses: [
      { title: "LearnCpp.com – Complete C++ Tutorial", provider: "LearnCpp", level: "Beginner", duration: "Self-paced", rating: 4.9, url: "https://www.learncpp.com/", free: FREE },
      { title: "C Programming Tutorial", provider: "Learn-C.org", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://www.learn-c.org/", free: FREE },
      { title: "C++ Full Course Videos", provider: "freeCodeCamp", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://www.freecodecamp.org/learn", free: FREE },
    ],
    projects: ["Custom shell", "Game engine renderer (OpenGL)", "Embedded sensor firmware"],
    certifications: ["CPA C++ Associate", "ARM Embedded certifications"],
  },
  {
    slug: "ai-ml",
    name: "AI / Machine Learning",
    icon: "Brain",
    tagline: "Models, training, evaluation and deployment.",
    demand: "Very High",
    avgSalary: "$110k – $190k",
    skills: ["Python", "Math/Stats", "PyTorch", "Scikit-learn", "MLOps", "Evaluation"],
    courses: [
      { title: "Machine Learning Crash Course", provider: "Google", level: "Beginner", duration: "~15h", rating: 4.8, url: "https://developers.google.com/machine-learning/crash-course", free: FREE },
      { title: "Practical Deep Learning", provider: "fast.ai", level: "Intermediate", duration: "Self-paced", rating: 4.9, url: "https://course.fast.ai/", free: FREE },
      { title: "Intro to Machine Learning", provider: "Kaggle Learn", level: "Beginner", duration: "~4h", rating: 4.8, url: "https://www.kaggle.com/learn", free: FREE },
    ],
    projects: ["Churn prediction + API", "Image classifier with monitoring", "RAG chatbot with evals"],
    certifications: ["AWS ML Specialty", "TensorFlow Developer Certificate"],
  },
  {
    slug: "generative-ai",
    name: "Generative AI / LLMs",
    icon: "Sparkles",
    tagline: "Prompting, RAG, agents and LLM apps.",
    demand: "Very High",
    avgSalary: "$120k – $200k",
    skills: ["Prompt Engineering", "RAG", "Vector DBs", "Agents", "Evals", "Fine-tuning"],
    courses: [
      { title: "Short Courses on LLMs & Agents", provider: "DeepLearning.AI", level: "Intermediate", duration: "1–4h each", rating: 4.8, url: "https://www.deeplearning.ai/short-courses/", free: FREE },
      { title: "OpenAI Cookbook (guides + code)", provider: "OpenAI", level: "Intermediate", duration: "Self-paced", rating: 4.8, url: "https://cookbook.openai.com/", free: FREE },
      { title: "Hugging Face Free Courses", provider: "Hugging Face", level: "Beginner", duration: "Self-paced", rating: 4.8, url: "https://huggingface.co/learn", free: FREE },
    ],
    projects: ["Docs Q&A with RAG", "Support agent with tools", "Eval harness for prompts"],
    certifications: ["DeepLearning.AI GenAI certs", "Azure AI Engineer Associate"],
  },
  {
    slug: "data-science",
    name: "Data Science",
    icon: "BarChart3",
    tagline: "Statistics, modeling and storytelling with data.",
    demand: "Very High",
    avgSalary: "$100k – $170k",
    skills: ["Statistics", "Python/R", "SQL", "Visualization", "Experimentation", "ML"],
    courses: [
      { title: "Kaggle Learn Micro-Courses", provider: "Kaggle", level: "Beginner", duration: "Self-paced", rating: 4.8, url: "https://www.kaggle.com/learn", free: FREE },
      { title: "Machine Learning with Python", provider: "freeCodeCamp", level: "Intermediate", duration: "~300h", rating: 4.8, url: "https://www.freecodecamp.org/learn", free: FREE },
      { title: "Machine Learning Crash Course", provider: "Google", level: "Beginner", duration: "~15h", rating: 4.8, url: "https://developers.google.com/machine-learning/crash-course", free: FREE },
    ],
    projects: ["A/B test analysis", "Customer segmentation", "End-to-end ML case study"],
    certifications: ["IBM Data Science", "Google Data Analytics → Advanced"],
  },
  {
    slug: "data-analytics",
    name: "Data Analytics",
    icon: "PieChart",
    tagline: "Dashboards, SQL, BI and business insight.",
    demand: "Very High",
    avgSalary: "$70k – $120k",
    skills: ["SQL", "Excel/Sheets", "Power BI/Tableau", "Python", "Storytelling", "dbt"],
    courses: [
      { title: "Data Analysis with Python", provider: "freeCodeCamp", level: "Beginner", duration: "~300h", rating: 4.8, url: "https://www.freecodecamp.org/learn", free: FREE },
      { title: "SQL Tutorial", provider: "Mode", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://mode.com/sql-tutorial/", free: FREE },
      { title: "Power BI Guided Learning", provider: "Microsoft Learn", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://learn.microsoft.com/", free: FREE },
    ],
    projects: ["Sales KPI dashboard", "Cohort retention analysis", "SQL + dbt pipeline"],
    certifications: ["Google Data Analytics", "PL-300 Power BI Data Analyst"],
  },
  {
    slug: "cloud",
    name: "Cloud (AWS/Azure/GCP)",
    icon: "Cloud",
    tagline: "Deploy, scale and secure cloud infrastructure.",
    demand: "Very High",
    avgSalary: "$100k – $170k",
    skills: ["Linux", "Networking", "IAM", "Containers", "IaC (Terraform)", "CI/CD"],
    courses: [
      { title: "AWS Skill Builder (free tier)", provider: "AWS", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://skillbuilder.aws/", free: FREE },
      { title: "Azure Administrator Path", provider: "Microsoft Learn", level: "Intermediate", duration: "Self-paced", rating: 4.7, url: "https://learn.microsoft.com/", free: FREE },
      { title: "Terraform Tutorials", provider: "HashiCorp Learn", level: "Intermediate", duration: "Self-paced", rating: 4.7, url: "https://developer.hashicorp.com/terraform/tutorials", free: FREE },
    ],
    projects: ["3-tier app on AWS", "Terraform multi-env setup", "Serverless image pipeline"],
    certifications: ["AWS SAA", "AZ-104", "CKA (if Kubernetes-heavy)"],
  },
  {
    slug: "devops",
    name: "DevOps / SRE",
    icon: "GitBranch",
    tagline: "CI/CD, Kubernetes, observability and reliability.",
    demand: "Very High",
    avgSalary: "$105k – $175k",
    skills: ["Linux", "Docker", "Kubernetes", "CI/CD", "Monitoring", "Scripting"],
    courses: [
      { title: "Free DevOps Courses", provider: "KodeKloud", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://kodekloud.com/", free: FREE },
      { title: "Kubernetes Official Tutorials", provider: "Kubernetes.io", level: "Intermediate", duration: "Self-paced", rating: 4.8, url: "https://kubernetes.io/docs/tutorials/", free: FREE },
      { title: "GitHub Actions Docs", provider: "GitHub", level: "Beginner", duration: "Self-paced", rating: 4.8, url: "https://docs.github.com/actions", free: FREE },
    ],
    projects: ["GitOps K8s deployment", "Blue/green + canary pipeline", "SLO dashboards + alerts"],
    certifications: ["CKA", "AWS DevOps Engineer Pro"],
  },
  {
    slug: "cybersecurity",
    name: "Cybersecurity",
    icon: "ShieldCheck",
    tagline: "Defend systems, networks and applications.",
    demand: "Very High",
    avgSalary: "$95k – $170k",
    skills: ["Networking", "Linux", "Security+", "SIEM", "Pentesting", "Cloud Sec"],
    courses: [
      { title: "Hands-on Hacking Labs (free tier)", provider: "TryHackMe", level: "Beginner", duration: "Self-paced", rating: 4.8, url: "https://tryhackme.com/", free: FREE },
      { title: "Cybersecurity Free Courses", provider: "Cisco Skills for All", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://skillsforall.com/", free: FREE },
      { title: "Security+ Free Video Course", provider: "Professor Messer", level: "Beginner", duration: "Self-paced", rating: 4.8, url: "https://www.professormesser.com/", free: FREE },
    ],
    projects: ["Home SOC lab (Wazuh)", "Web vuln write-ups", "Cloud hardening baseline"],
    certifications: ["Security+", "SC-100 / CISSP path"],
  },
  {
    slug: "networking",
    name: "Networking",
    icon: "Network",
    tagline: "Routing, switching, cloud networks and troubleshooting.",
    demand: "High",
    avgSalary: "$75k – $130k",
    skills: ["TCP/IP", "DNS/DHCP", "Routing/Switching", "Wireshark", "VPNs", "Cloud VPC"],
    courses: [
      { title: "Networking Free Courses", provider: "Cisco Skills for All", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://skillsforall.com/", free: FREE },
      { title: "Network+ Free Video Course", provider: "Professor Messer", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://www.professormesser.com/", free: FREE },
      { title: "Wireshark Documentation & Labs", provider: "Wireshark", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://www.wireshark.org/docs/", free: FREE },
    ],
    projects: ["GNS3 enterprise topology", "Wireshark analysis pack", "Hybrid cloud VPC design"],
    certifications: ["CCNA", "Network+"],
  },
  {
    slug: "databases",
    name: "Databases",
    icon: "Database",
    tagline: "SQL, modeling, performance and data engineering basics.",
    demand: "High",
    avgSalary: "$85k – $145k",
    skills: ["SQL", "Modeling", "Indexing", "Postgres", "MongoDB", "Redis"],
    courses: [
      { title: "PostgreSQL Tutorial (official)", provider: "PostgreSQL", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://www.postgresql.org/docs/current/tutorial.html", free: FREE },
      { title: "Interactive SQL Lessons", provider: "SQLBolt", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://sqlbolt.com/", free: FREE },
      { title: "MongoDB University", provider: "MongoDB", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://university.mongodb.com/", free: FREE },
    ],
    projects: ["Normalized e-commerce schema", "Slow-query tuning report", "CDC pipeline demo"],
    certifications: ["Oracle SQL Associate", "MongoDB Associate"],
  },
  {
    slug: "ui-ux",
    name: "UI/UX Design",
    icon: "Palette",
    tagline: "Research, wireframes, design systems and prototyping.",
    demand: "High",
    avgSalary: "$70k – $125k",
    skills: ["Figma", "Research", "Wireframing", "Design Systems", "Prototyping", "Usability"],
    courses: [
      { title: "Free Design Lessons", provider: "Hack Design", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://hackdesign.org/", free: FREE },
      { title: "Laws of UX (design principles)", provider: "Laws of UX", level: "Beginner", duration: "Self-paced", rating: 4.8, url: "https://lawsofux.com/", free: FREE },
      { title: "Figma Help & Tutorials", provider: "Figma", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://help.figma.com/", free: FREE },
    ],
    projects: ["End-to-end case study x3", "Design system in Figma", "Usability test report"],
    certifications: ["Google UX Design", "NN/g UX Certification path"],
  },
  {
    slug: "mobile-development",
    name: "Mobile Development",
    icon: "Smartphone",
    tagline: "iOS, Android and cross-platform apps.",
    demand: "High",
    avgSalary: "$85k – $150k",
    skills: ["Kotlin/Swift", "Flutter/React Native", "REST", "State Mgmt", "Push/Store", "Testing"],
    courses: [
      { title: "Flutter Codelabs", provider: "Flutter (Google)", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://docs.flutter.dev/codelabs", free: FREE },
      { title: "Android Basics with Compose", provider: "Google Developers", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://developer.android.com/courses", free: FREE },
      { title: "React Native Tutorial", provider: "Meta", level: "Intermediate", duration: "Self-paced", rating: 4.6, url: "https://reactnative.dev/docs/tutorial", free: FREE },
    ],
    projects: ["Habit tracker app", "Chat + offline sync app", "Published store app"],
    certifications: ["Google Associate Android Dev", "Flutter portfolio + store links"],
  },
  {
    slug: "cse-core",
    name: "CSE Core / CS Fundamentals",
    icon: "GraduationCap",
    tagline: "DSA, OS, DBMS, CN and placements prep.",
    demand: "Very High",
    avgSalary: "$80k – $150k",
    skills: ["DSA", "OS", "DBMS", "Computer Networks", "OOP", "Aptitude"],
    courses: [
      { title: "CS50x – Intro to Computer Science", provider: "Harvard", level: "Beginner", duration: "12 weeks", rating: 4.9, url: "https://cs50.harvard.edu/x/", free: FREE },
      { title: "NeetCode 150 DSA Practice", provider: "NeetCode", level: "Intermediate", duration: "Self-paced", rating: 4.9, url: "https://neetcode.io/", free: FREE },
      { title: "DSA Tutorial", provider: "GeeksforGeeks", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://www.geeksforgeeks.org/", free: FREE },
    ],
    projects: ["DSA patterns repo", "Mini OS shell", "DBMS mini project"],
    certifications: ["University grades + LeetCode profile", "Codeforces / Hackathons"],
  },
  {
    slug: "engineering-core",
    name: "Engineering (Core + Interdisciplinary)",
    icon: "Wrench",
    tagline: "Core engineering, robotics, CAD and systems thinking.",
    demand: "Stable",
    avgSalary: "$65k – $120k",
    skills: ["Math/Physics", "CAD", "MATLAB/Python", "Embedded", "Control Systems", "Documentation"],
    courses: [
      { title: "Free Engineering Courses (NPTEL)", provider: "NPTEL / SWAYAM", level: "Beginner", duration: "8–12 weeks", rating: 4.7, url: "https://nptel.ac.in/", free: FREE },
      { title: "MATLAB Onramp", provider: "MathWorks", level: "Beginner", duration: "2h", rating: 4.7, url: "https://matlabacademy.mathworks.com/", free: FREE },
      { title: "Arduino Documentation & Tutorials", provider: "Arduino", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://docs.arduino.cc/", free: FREE },
    ],
    projects: ["CAD assembly + simulation", "Arduino robot", "Data-logging rig"],
    certifications: ["SolidWorks CSWA", "University + internship proof"],
  },
  {
    slug: "business",
    name: "Business / Management",
    icon: "Briefcase",
    tagline: "Strategy, operations, product and leadership.",
    demand: "High",
    avgSalary: "$70k – $140k",
    skills: ["Strategy", "Analytics", "Product", "Finance Basics", "Leadership", "Communication"],
    courses: [
      { title: "PMI Kickoff (project basics)", provider: "PMI", level: "Beginner", duration: "~4h", rating: 4.6, url: "https://www.pmi.org/kickoff", free: FREE },
      { title: "HP LIFE Business Courses", provider: "HP Foundation", level: "Beginner", duration: "Self-paced", rating: 4.6, url: "https://www.life-global.org/", free: FREE },
      { title: "Free Business & Management Courses", provider: "Saylor Academy", level: "Beginner", duration: "Self-paced", rating: 4.6, url: "https://www.saylor.org/", free: FREE },
    ],
    projects: ["Business case teardown", "Go-to-market plan", "Ops dashboard"],
    certifications: ["CAPM / PMP path", "Google Project Management"],
  },
  {
    slug: "finance",
    name: "Finance",
    icon: "DollarSign",
    tagline: "Modeling, markets, accounting and analysis.",
    demand: "High",
    avgSalary: "$75k – $150k",
    skills: ["Excel", "Accounting", "Valuation", "SQL", "Risk", "Reporting"],
    courses: [
      { title: "Varsity – Stock Markets & Finance", provider: "Zerodha", level: "Beginner", duration: "Self-paced", rating: 4.8, url: "https://zerodha.com/varsity/", free: FREE },
      { title: "Corporate Finance Lectures", provider: "NYU Stern (Damodaran)", level: "Intermediate", duration: "Self-paced", rating: 4.8, url: "https://pages.stern.nyu.edu/~adamodar/", free: FREE },
      { title: "Finance & Capital Markets", provider: "Khan Academy", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://www.khanacademy.org/", free: FREE },
    ],
    projects: ["DCF model", "Portfolio backtest", "Budgeting dashboard"],
    certifications: ["CFA path", "FMVA (CFI)"],
  },
  {
    slug: "marketing",
    name: "Marketing / Digital Marketing",
    icon: "Megaphone",
    tagline: "SEO, content, ads, analytics and growth.",
    demand: "High",
    avgSalary: "$60k – $120k",
    skills: ["SEO", "Content", "Google Ads", "Social", "Email", "Analytics"],
    courses: [
      { title: "Content Marketing Certification", provider: "HubSpot Academy", level: "Beginner", duration: "~6h", rating: 4.7, url: "https://academy.hubspot.com/", free: FREE },
      { title: "Google Skillshop (Ads & Analytics)", provider: "Google", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://skillshop.withgoogle.com/", free: FREE },
      { title: "Semrush Academy (SEO & Content)", provider: "Semrush", level: "Beginner", duration: "Self-paced", rating: 4.6, url: "https://www.semrush.com/academy/", free: FREE },
    ],
    projects: ["SEO audit + fix", "Ad campaign case", "Content calendar + newsletter"],
    certifications: ["Google Ads", "HubSpot"],
  },
  {
    slug: "design",
    name: "Design (Graphic / Product)",
    icon: "PenTool",
    tagline: "Visual design, branding and motion basics.",
    demand: "Growing",
    avgSalary: "$60k – $115k",
    skills: ["Figma", "Typography", "Color", "Branding", "Illustrator", "Motion"],
    courses: [
      { title: "Canva Design School", provider: "Canva", level: "Beginner", duration: "Self-paced", rating: 4.6, url: "https://designschool.canva.com/", free: FREE },
      { title: "Free Graphic Design Diplomas", provider: "Alison", level: "Beginner", duration: "Self-paced", rating: 4.5, url: "https://alison.com/", free: FREE },
      { title: "Free Design Tutorials", provider: "GCFGlobal", level: "Beginner", duration: "Self-paced", rating: 4.6, url: "https://edu.gcfglobal.org/", free: FREE },
    ],
    projects: ["Brand kit", "Landing page UI pack", "Motion intro"],
    certifications: ["Adobe Certified", "Portfolio + Dribbble"],
  },
  {
    slug: "healthcare-tech",
    name: "Healthcare / Health Informatics",
    icon: "HeartPulse",
    tagline: "Clinical basics, health data and digital health.",
    demand: "Growing",
    avgSalary: "$70k – $130k",
    skills: ["Biology Basics", "Health Data", "HIPAA", "SQL", "EHR", "Research"],
    courses: [
      { title: "OpenWHO Health Courses", provider: "World Health Organization", level: "Beginner", duration: "Self-paced", rating: 4.6, url: "https://openwho.org/", free: FREE },
      { title: "Health & Medicine", provider: "Khan Academy", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://www.khanacademy.org/", free: FREE },
      { title: "Public Health OpenCourseWare", provider: "Johns Hopkins", level: "Beginner", duration: "Self-paced", rating: 4.6, url: "https://ocw.jhsph.edu/", free: FREE },
    ],
    projects: ["De-identified EHR dashboard", "Symptom triage prototype", "Clinical trial analysis"],
    certifications: ["CAHIMS", "HIPAA + research ethics"],
  },
];
