export type Course = {
  title: string;
  provider: string;
  level: string;
  duration: string;
  rating: number;
  url: string;
};

export type CareerField = {
  slug: string;
  name: string;
  icon: string;
  tagline: string;
  demand: "Very High" | "High" | "Growing" | "Stable";
  avgSalary: string;
  skills: string[];
  courses: Course[];
  projects: string[];
  certifications: string[];
};

export const CAREER_FIELDS: CareerField[] = [
  {
    slug: "software-development",
    name: "Software Development",
    icon: "Code2",
    tagline: "Build applications, backends and systems with modern stacks.",
    demand: "Very High",
    avgSalary: "$90k – $160k",
    skills: ["Data Structures", "Algorithms", "Git", "System Design", "Testing", "APIs"],
    courses: [
      { title: "Meta Back-End Developer Professional", provider: "Coursera", level: "Beginner", duration: "8 months", rating: 4.8, url: "https://www.coursera.org/professional-certificates/meta-back-end-developer" },
      { title: "The Complete JavaScript Course", provider: "Udemy", level: "Beginner", duration: "69h", rating: 4.7, url: "https://www.udemy.com/course/the-complete-javascript-course/" },
      { title: "System Design Primer (free)", provider: "GitHub", level: "Intermediate", duration: "Self-paced", rating: 4.9, url: "https://github.com/donnemartin/system-design-primer" },
    ],
    projects: ["REST API with auth + tests", "Real-time chat app", "URL shortener with analytics"],
    certifications: ["Meta Back-End Developer", "AWS Certified Developer – Associate"],
  },
  {
    slug: "web-development",
    name: "Web Development",
    icon: "Globe",
    tagline: "Frontend, backend and full-stack web apps.",
    demand: "Very High",
    avgSalary: "$75k – $140k",
    skills: ["HTML/CSS", "JavaScript", "React/Next.js", "Node.js", "Tailwind", "Databases"],
    courses: [
      { title: "The Web Developer Bootcamp", provider: "Udemy", level: "Beginner", duration: "74h", rating: 4.7, url: "https://www.udemy.com/course/the-web-developer-bootcamp/" },
      { title: "Next.js App Router Fundamentals", provider: "Vercel Learn", level: "Intermediate", duration: "12h", rating: 4.8, url: "https://nextjs.org/learn" },
      { title: "Full Stack Open", provider: "University of Helsinki", level: "Intermediate", duration: "Self-paced", rating: 4.9, url: "https://fullstackopen.com/en/" },
    ],
    projects: ["Portfolio + blog with CMS", "E-commerce store with payments", "SaaS dashboard with auth"],
    certifications: ["Meta Front-End Developer", "AWS Cloud Practitioner"],
  },
  {
    slug: "python",
    name: "Python",
    icon: "FileCode",
    tagline: "Scripting, automation, backends and data.",
    demand: "Very High",
    avgSalary: "$85k – $150k",
    skills: ["Python", "OOP", "APIs", "Pandas", "Django/Flask", "Testing"],
    courses: [
      { title: "Python for Everybody", provider: "Coursera", level: "Beginner", duration: "8 months", rating: 4.8, url: "https://www.coursera.org/specializations/python" },
      { title: "100 Days of Code: Python Bootcamp", provider: "Udemy", level: "Beginner", duration: "65h", rating: 4.7, url: "https://www.udemy.com/course/100-days-of-code/" },
      { title: "Django for Everybody", provider: "Coursera", level: "Intermediate", duration: "4 months", rating: 4.7, url: "https://www.coursera.org/specializations/django" },
    ],
    projects: ["Automation toolkit", "Django REST marketplace", "Data analysis notebook pack"],
    certifications: ["PCAP Python Associate", "Django / DRF portfolio"],
  },
  {
    slug: "java",
    name: "Java",
    icon: "Coffee",
    tagline: "Enterprise backends, Android and Spring systems.",
    demand: "High",
    avgSalary: "$85k – $145k",
    skills: ["Java", "Spring Boot", "SQL", "Microservices", "JUnit", "Kafka"],
    courses: [
      { title: "Java Programming Masterclass", provider: "Udemy", level: "Beginner", duration: "80h", rating: 4.6, url: "https://www.udemy.com/course/java-the-complete-java-developer-course/" },
      { title: "Spring Framework Specialization", provider: "Coursera", level: "Intermediate", duration: "4 months", rating: 4.6, url: "https://www.coursera.org/learn/spring-framework" },
      { title: "Data Structures in Java", provider: "Coursera", level: "Intermediate", duration: "6 weeks", rating: 4.7, url: "https://www.coursera.org/specializations/data-structures-algorithms" },
    ],
    projects: ["Banking REST API (Spring)", "Inventory microservices", "Android expense tracker"],
    certifications: ["Oracle Certified Associate: Java", "Spring Certified Professional"],
  },
  {
    slug: "cpp-c",
    name: "C / C++",
    icon: "Cpu",
    tagline: "Systems, embedded, game engines and performance.",
    demand: "High",
    avgSalary: "$90k – $155k",
    skills: ["C", "C++", "Memory Management", "STL", "Multithreading", "CMake"],
    courses: [
      { title: "C++ Nanodegree Foundations", provider: "Udacity", level: "Beginner", duration: "4 months", rating: 4.6, url: "https://www.udacity.com/course/c-plus-plus-nanodegree--nd213" },
      { title: "Beginning C++ Programming", provider: "Udemy", level: "Beginner", duration: "40h", rating: 4.6, url: "https://www.udemy.com/course/beginning-c-plus-plus-programming/" },
      { title: "Embedded Systems (UT Austin)", provider: "edX", level: "Intermediate", duration: "Self-paced", rating: 4.7, url: "https://www.edx.org/learn/embedded-systems" },
    ],
    projects: ["Custom shell", "Game engine renderer (OpenGL)", "Embedded sensor firmware"],
    certifications: ["CPA C++ Associate", "ARM Embedded certifications"],
  },
  {
    slug: "ai-ml",
    name: "AI / Machine Learning",
    icon: "Brain",
    tagline: "Models, training, evaluation and deployment.",
    demand: "Very High",
    avgSalary: "$110k – $190k",
    skills: ["Python", "Math/Stats", "PyTorch", "Scikit-learn", "MLOps", "Evaluation"],
    courses: [
      { title: "Machine Learning Specialization", provider: "Coursera (DeepLearning.AI)", level: "Beginner", duration: "3 months", rating: 4.9, url: "https://www.coursera.org/specializations/machine-learning-introduction" },
      { title: "Deep Learning Specialization", provider: "Coursera", level: "Intermediate", duration: "4 months", rating: 4.9, url: "https://www.coursera.org/specializations/deep-learning" },
      { title: "MLOps Specialization", provider: "Coursera", level: "Advanced", duration: "3 months", rating: 4.7, url: "https://www.coursera.org/specializations/mlops-duke" },
    ],
    projects: ["Churn prediction + API", "Image classifier with monitoring", "RAG chatbot with evals"],
    certifications: ["AWS ML Specialty", "TensorFlow Developer Certificate"],
  },
  {
    slug: "generative-ai",
    name: "Generative AI / LLMs",
    icon: "Sparkles",
    tagline: "Prompting, RAG, agents and LLM apps.",
    demand: "Very High",
    avgSalary: "$120k – $200k",
    skills: ["Prompt Engineering", "RAG", "Vector DBs", "Agents", "Evals", "Fine-tuning"],
    courses: [
      { title: "Generative AI with LLMs", provider: "Coursera (AWS + DeepLearning.AI)", level: "Intermediate", duration: "3 months", rating: 4.8, url: "https://www.coursera.org/learn/generative-ai-with-llms" },
      { title: "LangChain for LLM App Dev", provider: "DeepLearning.AI", level: "Intermediate", duration: "Short course", rating: 4.8, url: "https://www.deeplearning.ai/short-courses/" },
      { title: "RAG + Agents cookbook", provider: "OpenAI Cookbook", level: "Intermediate", duration: "Self-paced", rating: 4.8, url: "https://cookbook.openai.com/" },
    ],
    projects: ["Docs Q&A with RAG", "Support agent with tools", "Eval harness for prompts"],
    certifications: ["DeepLearning.AI GenAI certs", "Azure AI Engineer Associate"],
  },
  {
    slug: "data-science",
    name: "Data Science",
    icon: "BarChart3",
    tagline: "Statistics, modeling and storytelling with data.",
    demand: "Very High",
    avgSalary: "$100k – $170k",
    skills: ["Statistics", "Python/R", "SQL", "Visualization", "Experimentation", "ML"],
    courses: [
      { title: "IBM Data Science Professional", provider: "Coursera", level: "Beginner", duration: "11 months", rating: 4.6, url: "https://www.coursera.org/professional-certificates/ibm-data-science" },
      { title: "Data Scientist Nanodegree", provider: "Udacity", level: "Intermediate", duration: "4 months", rating: 4.6, url: "https://www.udacity.com/course/data-scientist-nanodegree--nd025" },
      { title: "Kaggle Learn (free)", provider: "Kaggle", level: "Beginner", duration: "Self-paced", rating: 4.8, url: "https://www.kaggle.com/learn" },
    ],
    projects: ["A/B test analysis", "Customer segmentation", "End-to-end ML case study"],
    certifications: ["IBM Data Science", "Google Data Analytics → Advanced"],
  },
  {
    slug: "data-analytics",
    name: "Data Analytics",
    icon: "PieChart",
    tagline: "Dashboards, SQL, BI and business insight.",
    demand: "Very High",
    avgSalary: "$70k – $120k",
    skills: ["SQL", "Excel/Sheets", "Power BI/Tableau", "Python", "Storytelling", "dbt"],
    courses: [
      { title: "Google Data Analytics", provider: "Coursera", level: "Beginner", duration: "6 months", rating: 4.8, url: "https://www.coursera.org/professional-certificates/google-data-analytics" },
      { title: "Microsoft Power BI Data Analyst", provider: "Coursera", level: "Beginner", duration: "5 months", rating: 4.7, url: "https://www.coursera.org/professional-certificates/microsoft-power-bi-data-analyst" },
      { title: "Mode SQL Tutorial (free)", provider: "Mode", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://mode.com/sql-tutorial/" },
    ],
    projects: ["Sales KPI dashboard", "Cohort retention analysis", "SQL + dbt pipeline"],
    certifications: ["Google Data Analytics", "PL-300 Power BI Data Analyst"],
  },
  {
    slug: "cloud",
    name: "Cloud (AWS/Azure/GCP)",
    icon: "Cloud",
    tagline: "Deploy, scale and secure cloud infrastructure.",
    demand: "Very High",
    avgSalary: "$100k – $170k",
    skills: ["Linux", "Networking", "IAM", "Containers", "IaC (Terraform)", "CI/CD"],
    courses: [
      { title: "AWS Solutions Architect Associate", provider: "Coursera / ACG", level: "Beginner", duration: "3 months", rating: 4.8, url: "https://www.coursera.org/learn/aws-cloud-solutions-architect" },
      { title: "AZ-104 Azure Administrator", provider: "Microsoft Learn", level: "Intermediate", duration: "Self-paced", rating: 4.7, url: "https://learn.microsoft.com/credentials/certifications/azure-administrator/" },
      { title: "Terraform Associate", provider: "HashiCorp Learn", level: "Intermediate", duration: "Self-paced", rating: 4.7, url: "https://developer.hashicorp.com/terraform/tutorials" },
    ],
    projects: ["3-tier app on AWS", "Terraform multi-env setup", "Serverless image pipeline"],
    certifications: ["AWS SAA", "AZ-104", "CKA (if Kubernetes-heavy)"],
  },
  {
    slug: "devops",
    name: "DevOps / SRE",
    icon: "GitBranch",
    tagline: "CI/CD, Kubernetes, observability and reliability.",
    demand: "Very High",
    avgSalary: "$105k – $175k",
    skills: ["Linux", "Docker", "Kubernetes", "CI/CD", "Monitoring", "Scripting"],
    courses: [
      { title: "DevOps on AWS Specialization", provider: "Coursera", level: "Intermediate", duration: "4 months", rating: 4.7, url: "https://www.coursera.org/specializations/aws-devops" },
      { title: "Certified Kubernetes Administrator", provider: "Linux Foundation", level: "Advanced", duration: "Self-paced", rating: 4.8, url: "https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/" },
      { title: "GitHub Actions docs (free)", provider: "GitHub", level: "Beginner", duration: "Self-paced", rating: 4.8, url: "https://docs.github.com/actions" },
    ],
    projects: ["GitOps K8s deployment", "Blue/green + canary pipeline", "SLO dashboards + alerts"],
    certifications: ["CKA", "AWS DevOps Engineer Pro"],
  },
  {
    slug: "cybersecurity",
    name: "Cybersecurity",
    icon: "ShieldCheck",
    tagline: "Defend systems, networks and applications.",
    demand: "Very High",
    avgSalary: "$95k – $170k",
    skills: ["Networking", "Linux", "Security+", "SIEM", "Pentesting", "Cloud Sec"],
    courses: [
      { title: "Google Cybersecurity Professional", provider: "Coursera", level: "Beginner", duration: "6 months", rating: 4.8, url: "https://www.coursera.org/professional-certificates/google-cybersecurity" },
      { title: "CompTIA Security+ (SY0-701)", provider: "CompTIA", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://www.comptia.org/certifications/security" },
      { title: "TryHackMe Jr Pentester (free tier)", provider: "TryHackMe", level: "Beginner", duration: "Self-paced", rating: 4.8, url: "https://tryhackme.com/" },
    ],
    projects: ["Home SOC lab (Wazuh)", "Web vuln write-ups", "Cloud hardening baseline"],
    certifications: ["Security+", "SC-100 / CISSP path"],
  },
  {
    slug: "networking",
    name: "Networking",
    icon: "Network",
    tagline: "Routing, switching, cloud networks and troubleshooting.",
    demand: "High",
    avgSalary: "$75k – $130k",
    skills: ["TCP/IP", "DNS/DHCP", "Routing/Switching", "Wireshark", "VPNs", "Cloud VPC"],
    courses: [
      { title: "CCNA 200-301", provider: "Cisco Skills", level: "Beginner", duration: "3-6 months", rating: 4.8, url: "https://www.cisco.com/site/US/en/learn/training-certifications/certifications/enterprise/ccna/index.html" },
      { title: "Network+ N10", provider: "CompTIA", level: "Beginner", duration: "Self-paced", rating: 4.6, url: "https://www.comptia.org/certifications/network" },
      { title: "Practical Networking (free)", provider: "YouTube / Labs", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://www.youtube.com/results?search_query=practical+networking" },
    ],
    projects: ["GNS3 enterprise topology", "Wireshark analysis pack", "Hybrid cloud VPC design"],
    certifications: ["CCNA", "Network+"],
  },
  {
    slug: "databases",
    name: "Databases",
    icon: "Database",
    tagline: "SQL, modeling, performance and data engineering basics.",
    demand: "High",
    avgSalary: "$85k – $145k",
    skills: ["SQL", "Modeling", "Indexing", "Postgres", "MongoDB", "Redis"],
    courses: [
      { title: "SQL for Data Science", provider: "Coursera", level: "Beginner", duration: "4 weeks", rating: 4.7, url: "https://www.coursera.org/learn/sql-for-data-science" },
      { title: "PostgreSQL Bootcamp", provider: "Udemy", level: "Beginner", duration: "20h", rating: 4.6, url: "https://www.udemy.com/course/sql-and-postgresql/" },
      { title: "MongoDB University (free)", provider: "MongoDB", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://university.mongodb.com/" },
    ],
    projects: ["Normalized e-commerce schema", "Slow-query tuning report", "CDC pipeline demo"],
    certifications: ["Oracle SQL Associate", "MongoDB Associate"],
  },
  {
    slug: "ui-ux",
    name: "UI/UX Design",
    icon: "Palette",
    tagline: "Research, wireframes, design systems and prototyping.",
    demand: "High",
    avgSalary: "$70k – $125k",
    skills: ["Figma", "Research", "Wireframing", "Design Systems", "Prototyping", "Usability"],
    courses: [
      { title: "Google UX Design Professional", provider: "Coursera", level: "Beginner", duration: "6 months", rating: 4.8, url: "https://www.coursera.org/professional-certificates/google-ux-design" },
      { title: "Designlab UX Academy Foundations", provider: "Designlab", level: "Beginner", duration: "4 weeks", rating: 4.6, url: "https://designlab.com/" },
      { title: "Refactoring UI (book)", provider: "Refactoring UI", level: "Intermediate", duration: "Self-paced", rating: 4.9, url: "https://www.refactoringui.com/" },
    ],
    projects: ["End-to-end case study x3", "Design system in Figma", "Usability test report"],
    certifications: ["Google UX Design", "NN/g UX Certification path"],
  },
  {
    slug: "mobile-development",
    name: "Mobile Development",
    icon: "Smartphone",
    tagline: "iOS, Android and cross-platform apps.",
    demand: "High",
    avgSalary: "$85k – $150k",
    skills: ["Kotlin/Swift", "Flutter/React Native", "REST", "State Mgmt", "Push/Store", "Testing"],
    courses: [
      { title: "Flutter & Dart Bootcamp", provider: "Udemy", level: "Beginner", duration: "30h", rating: 4.6, url: "https://www.udemy.com/course/flutter-bootcamp-with-dart/" },
      { title: "Android Basics with Compose", provider: "Google Developers", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://developer.android.com/courses" },
      { title: "React Native docs path", provider: "Meta", level: "Intermediate", duration: "Self-paced", rating: 4.6, url: "https://reactnative.dev/docs/tutorial" },
    ],
    projects: ["Habit tracker app", "Chat + offline sync app", "Published store app"],
    certifications: ["Google Associate Android Dev", "Flutter portfolio + store links"],
  },
  {
    slug: "cse-core",
    name: "CSE Core / CS Fundamentals",
    icon: "GraduationCap",
    tagline: "DSA, OS, DBMS, CN and placements prep.",
    demand: "Very High",
    avgSalary: "$80k – $150k",
    skills: ["DSA", "OS", "DBMS", "Computer Networks", "OOP", "Aptitude"],
    courses: [
      { title: "CS50x (Harvard, free)", provider: "edX", level: "Beginner", duration: "12 weeks", rating: 4.9, url: "https://cs50.harvard.edu/x/" },
      { title: "NeetCode 150 (free)", provider: "NeetCode", level: "Intermediate", duration: "Self-paced", rating: 4.9, url: "https://neetcode.io/" },
      { title: "GATE / Placement OS+DBMS playlists", provider: "YouTube", level: "Beginner", duration: "Self-paced", rating: 4.7, url: "https://www.youtube.com/results?search_query=gate+cse+os+dbms" },
    ],
    projects: ["DSA patterns repo", "Mini OS shell", "DBMS mini project"],
    certifications: ["University grades + LeetCode profile", "Codeforces / Hackathons"],
  },
  {
    slug: "engineering-core",
    name: "Engineering (Core + Interdisciplinary)",
    icon: "Wrench",
    tagline: "Core engineering, robotics, CAD and systems thinking.",
    demand: "Stable",
    avgSalary: "$65k – $120k",
    skills: ["Math/Physics", "CAD", "MATLAB/Python", "Embedded", "Control Systems", "Documentation"],
    courses: [
      { title: "Engineering Mechanics", provider: "Coursera", level: "Beginner", duration: "8 weeks", rating: 4.6, url: "https://www.coursera.org/learn/engineering-mechanics-statics" },
      { title: "MATLAB Onramp (free)", provider: "MathWorks", level: "Beginner", duration: "2h", rating: 4.7, url: "https://matlabacademy.mathworks.com/" },
      { title: "Modern Robotics Specialization", provider: "Coursera", level: "Intermediate", duration: "4 months", rating: 4.8, url: "https://www.coursera.org/specializations/modernrobotics" },
    ],
    projects: ["CAD assembly + simulation", "Arduino robot", "Data-logging rig"],
    certifications: ["SolidWorks CSWA", "University + internship proof"],
  },
  {
    slug: "business",
    name: "Business / Management",
    icon: "Briefcase",
    tagline: "Strategy, operations, product and leadership.",
    demand: "High",
    avgSalary: "$70k – $140k",
    skills: ["Strategy", "Analytics", "Product", "Finance Basics", "Leadership", "Communication"],
    courses: [
      { title: "Google Project Management", provider: "Coursera", level: "Beginner", duration: "6 months", rating: 4.8, url: "https://www.coursera.org/professional-certificates/google-project-management" },
      { title: "Wharton Business Foundations", provider: "Coursera", level: "Beginner", duration: "5 months", rating: 4.7, url: "https://www.coursera.org/specializations/wharton-business-foundations" },
      { title: "Product Management (Reforge samples)", provider: "Reforge", level: "Intermediate", duration: "Self-paced", rating: 4.6, url: "https://www.reforge.com/" },
    ],
    projects: ["Business case teardown", "Go-to-market plan", "Ops dashboard"],
    certifications: ["CAPM / PMP path", "Google Project Management"],
  },
  {
    slug: "finance",
    name: "Finance",
    icon: "DollarSign",
    tagline: "Modeling, markets, accounting and analysis.",
    demand: "High",
    avgSalary: "$75k – $150k",
    skills: ["Excel", "Accounting", "Valuation", "SQL", "Risk", "Reporting"],
    courses: [
      { title: "Finance & Quantitative Modeling (Wharton)", provider: "Coursera", level: "Beginner", duration: "6 months", rating: 4.7, url: "https://www.coursera.org/specializations/wharton-quantitative-modeling" },
      { title: "CFA Investment Foundations", provider: "CFA Institute", level: "Beginner", duration: "Self-paced", rating: 4.6, url: "https://www.cfainstitute.org/en/membership/professional-development/refresher-readings" },
      { title: "Corporate Finance (NYU free)", provider: "NYU Stern", level: "Intermediate", duration: "Self-paced", rating: 4.8, url: "https://pages.stern.nyu.edu/~adamodar/" },
    ],
    projects: ["DCF model", "Portfolio backtest", "Budgeting dashboard"],
    certifications: ["CFA path", "FMVA (CFI)"],
  },
  {
    slug: "marketing",
    name: "Marketing / Digital Marketing",
    icon: "Megaphone",
    tagline: "SEO, content, ads, analytics and growth.",
    demand: "High",
    avgSalary: "$60k – $120k",
    skills: ["SEO", "Content", "Google Ads", "Social", "Email", "Analytics"],
    courses: [
      { title: "Google Digital Marketing & E-commerce", provider: "Coursera", level: "Beginner", duration: "6 months", rating: 4.8, url: "https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce" },
      { title: "HubSpot Content Marketing (free)", provider: "HubSpot", level: "Beginner", duration: "6h", rating: 4.7, url: "https://academy.hubspot.com/" },
      { title: "Meta Social Media Marketing", provider: "Coursera", level: "Beginner", duration: "5 months", rating: 4.7, url: "https://www.coursera.org/professional-certificates/facebook-social-media-marketing" },
    ],
    projects: ["SEO audit + fix", "Ad campaign case", "Content calendar + newsletter"],
    certifications: ["Google Ads", "HubSpot"],
  },
  {
    slug: "design",
    name: "Design (Graphic / Product)",
    icon: "PenTool",
    tagline: "Visual design, branding and motion basics.",
    demand: "Growing",
    avgSalary: "$60k – $115k",
    skills: ["Figma", "Typography", "Color", "Branding", "Illustrator", "Motion"],
    courses: [
      { title: "CalArts Graphic Design (free audit)", provider: "Coursera", level: "Beginner", duration: "4 months", rating: 4.7, url: "https://www.coursera.org/specializations/graphic-design" },
      { title: "Figma UI Design Essentials", provider: "Udemy", level: "Beginner", duration: "10h", rating: 4.6, url: "https://www.udemy.com/course/figma-ui-ux-design-essentials/" },
      { title: "Canva Design School (free)", provider: "Canva", level: "Beginner", duration: "Self-paced", rating: 4.6, url: "https://designschool.canva.com/" },
    ],
    projects: ["Brand kit", "Landing page UI pack", "Motion intro"],
    certifications: ["Adobe Certified", "Portfolio + Dribbble"],
  },
  {
    slug: "healthcare-tech",
    name: "Healthcare / Health Informatics",
    icon: "HeartPulse",
    tagline: "Clinical basics, health data and digital health.",
    demand: "Growing",
    avgSalary: "$70k – $130k",
    skills: ["Biology Basics", "Health Data", "HIPAA", "SQL", "EHR", "Research"],
    courses: [
      { title: "AI for Medicine", provider: "Coursera", level: "Intermediate", duration: "4 months", rating: 4.8, url: "https://www.coursera.org/specializations/ai-for-medicine" },
      { title: "Health Informatics (JHU)", provider: "Coursera", level: "Beginner", duration: "4 months", rating: 4.6, url: "https://www.coursera.org/specializations/health-informatics" },
      { title: "Biostatistics (free)", provider: "Coursera", level: "Beginner", duration: "4 weeks", rating: 4.6, url: "https://www.coursera.org/learn/biostatistics" },
    ],
    projects: ["De-identified EHR dashboard", "Symptom triage prototype", "Clinical trial analysis"],
    certifications: ["CAHIMS", "HIPAA + research ethics"],
  },
];
